### ISSUE TITLE
Two errors when new questions are submitted

### ISSUE THREAD

**Issue by Sam-Black-0013** [owldesign/QARR#1]
1. When opening the dashboard:

A. Impossible to access an attribute ("title") on a null variable.
in owldesign/qarr/src/templates/dashboard/_includes/widget-recent.twig

B. Calling unknown method: owldesign\qarr\elements\Question::getFlags()
in owldesign/qarr/src/templates/dashboard/_includes/widget-recent.twig

2. When opening a question page:

A. Impossible to access an attribute ("title") on a null variable.
in owldesign/qarr/src/templates/questions/_edit.twig

B. Impossible to invoke a method ("getCpEditUrl") on a null variable.
in owldesign/qarr/src/templates/questions/_edit.twig

etc...
They are probably in other templates

**Comment by owldesign** [comment]
@Sam-Black-0013 

Can you please provide these:
• Plugin Version
• Craft Version
• PHP Version

**Comment by owldesign** [comment]
Its probably something to do with the fact that a product most of been deleted or commerce plugin was uninstalled. 

Please pull latest version of the plugin and see if the issue is resovled. Version 1.0.9

**Comment by Sam-Black-0013** [comment]
Plugin Version 1.0.9(updated)
Craft Version 3.1.12
PHP Version 7.1

**Comment by owldesign** [comment]
@Sam-Black-0013 so you're getting the same errors with the new 1.0.9 version as well?

**Comment by Sam-Black-0013** [comment]
nope, not any more. Thank you for your help ^^
