### ISSUE TITLE
error when displaying the questions in the cp

### ISSUE THREAD

**Issue by Sam-Black-0013** [owldesign/QARR#10]
I get an error when trying to open the edit page of a question in the cp
"Impossible to access an attribute ("id") on a null variable. in vendor\owldesign\qarr\src\templates\questions\_edit.twig     line 222"

**Comment by owldesign** [comment]
Hey @Sam-Black-0013 do you mind pulling the latest version 1.1.5 and let me know if you still having issues?

**Comment by owldesign** [comment]
closing this, seems stale
