### ISSUE TITLE
Author's name not showing up if it only has one word.

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#15]
For some reason, the author's name isn't rendering on the frontend if the author only supplied a first name (one word) using `{{ review.author }}` or `{{ question.author }}`.

`{{ review.fullName|split(' ')[0] }}` and `{{ question.fullName|split(' ')[0] }}` works as a workaround.

**Comment by owldesign** [comment]
I've made some updates, pull latest and let me know if you still having issues.
