### ISSUE TITLE
[Feature request] File upload

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#16]
It would be great to be able to include an assets field in the displays that can be used to upload images connected to a question or review. Not sure if or how this is doable within custom templates.

**Comment by owldesign** [comment]
@23d1 Yeah I was trying to wrap my head around how to do Displays for custom templates.

Only way I can think is you provide display handle and recreate those fields making sure field handle names match.. for example:

`<input type="hidden" name="displayHandle" value="extraFieldsDisplay">`

and in your display you would have these for example

![image](https://user-images.githubusercontent.com/438764/60381246-754d6b00-9a06-11e9-91dd-99ff34f4587e.png)

Then your form would need to be something like this..

```
<input type="hidden" name="displayHandle" value="extraFieldsDisplay">

<input type="text" name="fields[yourLocation]" placeholder="Enter your location" />

<select name="fields[yourGender]>
    <option value="male">Male</option>
    <option value="female">Female</option>
</select>
```

To the topic of the file uploads, it would work simiar, add field to display then add it to form..

`<input type="file" name="fields[assetHandleName][]" />`

If people chose to go the custom template way and still use displays, this seem ok to me. What you think?

**Comment by 23d1** [comment]
I think that sounds good. The only trouble I have is that asset fields are not showing up under displays. Not sure if it's a user error. :)

**Comment by owldesign** [comment]
Hey, I didn't have asses as allowed field yet. V 1.1.6 I pushed up should now have access to Assets.

Here's more docs on the topic https://docs.qarr.tools/custom/displays/

**Comment by 23d1** [comment]
You are a gem! Thanks! Should be done with the trial soon and put some dollars into it for the build I'm working on. :)
