### ISSUE TITLE
Can't access QARR backend after updating

### ISSUE THREAD

**Issue by edwardpmartinez** [owldesign/QARR#17]
The error is: Impossible to access an attribute ("foodAndBeverage") on a null variable.

in /home/vagrant/code/testing/vendor/owldesign/qarr/src/templates/_elements/element-element.twig at line 4

**Comment by owldesign** [comment]
@edwardpmartinez I've pushed up update (1.1.8). That should fix it!

Thanks for reporting!

**Comment by edwardpmartinez** [comment]
Can confirm that the issue is fixed
