### ISSUE TITLE
[Feature request]: Allow modifications to the email sent via reply by email

### ISSUE THREAD

**Issue by edwardpmartinez** [owldesign/QARR#19]
It would be nice if the email sent by QARR can be adjusted. Right now, it is sending an email with a very bright purple background.

**Comment by owldesign** [comment]
I've added this to v 1.2.0

You can find it under `qarr/campaigns/email-templates/`

Here are the docs [Email Templates](https://docs.qarr.tools/campaigns/email-templates) I'll update the docs with some screenshots in few days.

**Comment by edwardpmartinez** [comment]
Noted, @owldesign! Closing this issue/request. Thank you for the hard work
