### ISSUE TITLE
Answer form returns a json 

### ISSUE THREAD

**Issue by Sam-Black-0013** [owldesign/QARR#2]
When i submit an answer form, the redirect url returns me a json response with "_successful-answer" template.
`return $this->asJson(['success'   => true, 'template'  => $template
 ]);`
setting the redirect url does not work. can you please check it
i set it to return to the old path but if i hit refresh, the form gets submitted again.

**Comment by owldesign** [comment]
Not sure how you managed to use that, because I've just added custom front end forms for things like that. Before it was all ajaxified. 

Check docs here for how to use the [Answer Form](https://docs.qarr.tools/custom/answers/)
