### ISSUE TITLE
[Feature request]: Make the backend QARR module conform to the Craft CMS look

### ISSUE THREAD

**Issue by edwardpmartinez** [owldesign/QARR#20]
Right now, the control panel QARR section employs heavy use of nonstandard elements. It looks out of place when you compare it to other sections of the Craft CMS interface (entries, dashboard, settings, etc.). It would be nice if the QARR backend can use the standard Craft CMS design language so it will look coherent with the rest of the elements (red instead of the purple, standard fonts instead of the custom fonts). Really love this plugin!

**Comment by owldesign** [comment]
Working on an option for this, stay tuned.

**Comment by edwardpmartinez** [comment]
Thank you, @owldesign. Will definitely stay tuned. Thank you for making such a compelling plugin!

**Comment by owldesign** [comment]
@edwardpmartinez version 1.2.0 should now start matching Craft UI. Going forward we'll keep it that way.

**Comment by edwardpmartinez** [comment]
Thank you for responding to my feedback, @owldesign! Your great plugin keeps getting better!
