### ISSUE TITLE
[Enhancement] Ability to answer questions from the admin panel.

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#24]
Would be great to be able to answer questions and just like commenting on reviews and so forth from the admin panel.

**Comment by Coalescent** [comment]
I just came here with the same request/issue. It is a great plugin but not being able to answer questions from the admin area makes the questions functionality somewhat useless if you do not want people submitting answers from the front end.

I suppose as a hack, one could only show the front end answer form if the current user was an administrator but it would be far more convenient to answer from the admin.

**Comment by owldesign** [comment]
Option to post answers via CP is now available.
