### ISSUE TITLE
Error viewing a newly created display

### ISSUE THREAD

**Issue by TomDeSmet** [owldesign/QARR#28]
When creating a new Display and afterwards clicking that Display in the CP, this error is generated and I'm unable to view the Display page.

`Argument 1 passed to craft\services\Sites::getSiteById() must be of the type int, string given, called in /Users/tom/Sites/jules-destrooper-dev/vendor/twig/twig/src/Extension/CoreExtension.php on line 1499`

Craft: 3.17.1
QARR: 1.2.1

**Comment by owldesign** [comment]
@TomDeSmet Can you update plugin to latest version and see if there is still an issue?

**Comment by TomDeSmet** [comment]
Still an issue. Even more, I can't even create a new display anymore, getting this error: `Unknown "namespaceAttributes" filter.`

**Comment by owldesign** [comment]
@TomDeSmet are you still running Craft 3.17.1? Or what is your current Craft version?

**Comment by owldesign** [comment]
I've also just pushed up another update.

Displays will now load layout designer based on Craft version you're running. This is in case you are running lower than Craft 3.5.0

**Comment by TomDeSmet** [comment]
We're still on 3.4, we haven't been able to update yet. I will check it out when we're able to upgrade.

**Comment by Lik22ml** [comment]
Same issue, Craft version 3.5.15 Latest, plugin vrsion, latest ass well, same error, please help

**Comment by owldesign** [comment]
I'm closing this one out because it should be resolved in newest update 1.2.8
