### ISSUE TITLE
Error when approving/rejecting pending reviews from widget

### ISSUE THREAD

**Issue by SandraSundqvist** [owldesign/QARR#33]
We're using the latest version of the plugin(1.2.7) and getting status 500 when approving or rejecting a review in the admin. Here is the error message: 

`Argument 2 passed to owldesign\\qarr\\services\\Elements::queryElements() must be of the type string, null given, called in /home/vagrant/sites/mr-bear-family-v2/vendor/owldesign/qarr/src/controllers/ElementsController.php on line 26`

Review does however get approved, so it still seems to work as expected(?), but we are also getting both a success message and an error message after clicking approve/reject on review.

![Error message and success message](https://user-images.githubusercontent.com/64203689/112299894-8f2de780-8c98-11eb-8f6b-2127768bed6f.png)

**Comment by cherrykoda** [comment]
I am getting the same issue, is there any update?

**Comment by owldesign** [comment]
Fixed in 1.2.8
