### ISSUE TITLE
Error on Edit for Campaigns, Displays and Rules

### ISSUE THREAD

**Issue by billmn** [owldesign/QARR#37]
When I try to edit a Display, Campaign or Rule this error was shown on CP:
```
Argument 1 passed to craft\services\Sites::getSiteById() must be of the type int, string given, called in /vendor/twig/twig/src/Extension/CoreExtension.php on line 1511
```

Probably related to: https://github.com/owldesign/QARR/issues/28

I'm using:
Craft CMS 3.6.15
QARR version 1.2.7

**Comment by jonXmack** [comment]
Also having this issue on Craft 3.6.15 with QARR 1.2.7

**Comment by owldesign** [comment]
Latest update should have fixe this (1.2.8).

let me know if that is not the case.
