### ISSUE TITLE
Don't override Craft CMS `json_decode` filter

### ISSUE THREAD

**Issue by billmn** [owldesign/QARR#38]
Now QARR overrides Craft CMS `json_decode` filter (https://craftcms.com/docs/3.x/dev/filters.html#json-decode) and it can cause some problems, like it return a `stdClass` object instead of an array.

Is it possibile to remove this filter? https://github.com/owldesign/QARR/blob/ae74b3c71908d37e83be975ed189750768cef9d3/src/web/twig/Extensions.php#L38

Thank you

**Comment by owldesign** [comment]
Done! Thanks! I got your other pull requests merged in as well. Thank you.
