### ISSUE TITLE
Plugin breaks when products with reviews are disabled or deleted.

### ISSUE THREAD

**Issue by cherrykoda** [owldesign/QARR#39]
When discontinued products are removed from Craft Commerce, the review plugin breaks. Dashboards display incorrect numbers, and views that would have included the removed products give a server error and become non-respondant. 

Reviews associated with products should be deleted OR they should be tackled to not rely on the product being within the CMS. We are currently stuck and the entire plugin is erroring with no way for us to fix it aside from manually clearing the database.

I was unable to find a support contact, aside from a slack link on the main QARR website that did not trigger when I clicked on it. Please let me know if there is a better way to contact someone.

**Craft Version:** Craft Pro 3.7.13
**Plugin Version:** 1.2.7
**PHP Version:** 7.4.20
**Multisite:** No

**Comment by owldesign** [comment]
Should be fixed in 1.28
