### ISSUE TITLE
The "write review" button doesn't work if the product title is too long

### ISSUE THREAD

**Issue by edwardpmartinez** [owldesign/QARR#4]
When the product title is short, the dialog box shows up. When the product title is too long, it does nothing. Tested on both staging and production environments. 
* Craft CMS 3.1.28
* QARR 1.0.9

**Comment by owldesign** [comment]
@edwardpmartinez I've tried super long title eg. `A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga A New Toga` and it worked for me.

Are there any console log errors for javascript?

**Comment by edwardpmartinez** [comment]
I updated the plugin to the newest version. I can confirm that the write reviews works even with long titles. Thank you so much.
