### ISSUE TITLE
The "reply by email" button in the Questions CP section doesn't work

### ISSUE THREAD

**Issue by edwardpmartinez** [owldesign/QARR#5]
Confirmed that my install has a working email setup (the send test email function works). When you click on the "reply by email" button, a red error shows up "An unknown error occured"

**Comment by owldesign** [comment]
@edwardpmartinez can you please check error logs and post them here?

If you have yii/craft debug toolbar check POST logs for something similar to bellow

![image](https://user-images.githubusercontent.com/438764/58770124-cc743300-8561-11e9-9db9-25e82bfa9e6a.png)

**Comment by owldesign** [comment]
@edwardpmartinez I've made some updates to the plugin, I'd pull the latest and check if you still having email issues?

**Comment by edwardpmartinez** [comment]
Hi @owldesign, I just updated to the latest version and I can't access QARR from the control panel. I opened a new issue

**Comment by edwardpmartinez** [comment]
After applying the latest update, the reply by email function is working.
