### ISSUE TITLE
Wrong status on index 

### ISSUE THREAD

**Issue by billmn** [owldesign/QARR#54]
When I update the status of a review (e.g. from "pending" to "approved") and return to the index, the table show the old status (even after a reload).

The only solution I found to solve the problem is to reset "Data caches" from the utility section.

Thoughts?

QARR: 1.3.2
Craft CMS: 3.7.52

**Comment by billmn** [comment]
@owldesign Any update on this?

**Comment by lionettiluca** [comment]
+1
