### ISSUE TITLE
[Request] Non-jquery JavaScript functionality

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#6]
Are there any plans on releasing a non-jquery version of this plugin?

If not, would it be possible to bundle or format the frontend to include jquery, as to not have to add that manually to the <head>?

Thanks!

**Comment by owldesign** [comment]
@23d1 I didn't have any plans for that, but I think I'm going to change it to vanilla javascript so to avoid any dependencies in the long run. I'll try to do that this week sometimes

**Comment by 23d1** [comment]
Perhaps a version that is completely without JavaScript would be a good idea as well. 

That way, one could build the functionality on top of what is working without. 

For example; that would mean clicking to write a review would update the page/navigate to a new page for input, then navigate to a new page for success or errors. Kind of how Contact Form works and so forth, where you navigate between pages, or update the current one. Then it would be up to the user to ajaxify that process.

**Comment by owldesign** [comment]
@23d1 true, yeah i'll look into making something that gives 2 options. Use JS or not.

Thanks

**Comment by owldesign** [comment]
Ok so with the new update it will load the jQuery scripts if people are not manually including them. I've also added an option for custom forms check here: https://docs.qarr.tools/custom/reviews/

**Comment by 23d1** [comment]
Fantastic work. The custom templating functionality solved this beautifully, as one is able to build custom functionality around that.
