### ISSUE TITLE
Ajax and callbacks

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#8]
Is there a way to reinitialize when a site is ajaxified? Using SWUP (similar to BarbaJS) and am not sure how to reinit the scripts. Will find a workaround for now.

**Comment by owldesign** [comment]
I also added a jquery plugin for this, would be great if you can give it a test.

Details here: https://docs.qarr.tools/core/details/

**Comment by 23d1** [comment]
Fantastic, will check this out. I've found another issue that I'll post separately.
