### ISSUE TITLE
The Craft admin panel is affected by QARR css

### ISSUE THREAD

**Issue by 23d1** [owldesign/QARR#9]
It looks like there's some interference in the admin panel in some places like dropdown menus from the QARR resources.

Example; 
![Screen Shot 2019-06-04 at 11 38 01 PM](https://user-images.githubusercontent.com/2627617/58935380-3804fe80-8722-11e9-94b2-e30ebf147515.png)

Possibly because the `.qarr` and `.qarr-tools` is being added to the `<body>` tag in the admin panel.

**Comment by owldesign** [comment]
Thanks, latest push should fix that.
